// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/helloService/helloService.proto

package go_micro_srv_helloService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for HelloService service

type HelloService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (HelloService_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (HelloService_PingPongService, error)
}

type helloService struct {
	c    client.Client
	name string
}

func NewHelloService(name string, c client.Client) HelloService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.helloService"
	}
	return &helloService{
		c:    c,
		name: name,
	}
}

func (c *helloService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "HelloService.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (HelloService_StreamService, error) {
	req := c.c.NewRequest(c.name, "HelloService.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &helloServiceStream{stream}, nil
}

type HelloService_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type helloServiceStream struct {
	stream client.Stream
}

func (x *helloServiceStream) Close() error {
	return x.stream.Close()
}

func (x *helloServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *helloServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *helloServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helloService) PingPong(ctx context.Context, opts ...client.CallOption) (HelloService_PingPongService, error) {
	req := c.c.NewRequest(c.name, "HelloService.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &helloServicePingPong{stream}, nil
}

type HelloService_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type helloServicePingPong struct {
	stream client.Stream
}

func (x *helloServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *helloServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *helloServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *helloServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *helloServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for HelloService service

type HelloServiceHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, HelloService_StreamStream) error
	PingPong(context.Context, HelloService_PingPongStream) error
}

func RegisterHelloServiceHandler(s server.Server, hdlr HelloServiceHandler, opts ...server.HandlerOption) error {
	type helloService interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type HelloService struct {
		helloService
	}
	h := &helloServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&HelloService{h}, opts...))
}

type helloServiceHandler struct {
	HelloServiceHandler
}

func (h *helloServiceHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.HelloServiceHandler.Call(ctx, in, out)
}

func (h *helloServiceHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.HelloServiceHandler.Stream(ctx, m, &helloServiceStreamStream{stream})
}

type HelloService_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type helloServiceStreamStream struct {
	stream server.Stream
}

func (x *helloServiceStreamStream) Close() error {
	return x.stream.Close()
}

func (x *helloServiceStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *helloServiceStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *helloServiceStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *helloServiceHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.HelloServiceHandler.PingPong(ctx, &helloServicePingPongStream{stream})
}

type HelloService_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type helloServicePingPongStream struct {
	stream server.Stream
}

func (x *helloServicePingPongStream) Close() error {
	return x.stream.Close()
}

func (x *helloServicePingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *helloServicePingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *helloServicePingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *helloServicePingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
